# Form implementation generated from reading ui file 'TrainerDetails.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from gui import Ui_SecondWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(436, 388)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        Binary = ""



        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 100, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(210, 250, 21, 16))
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 250, 61, 16))
        self.label_7.setObjectName("label_7")





        self.TrainerIDlineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.TrainerIDlineEdit.setGeometry(QtCore.QRect(160, 20, 21, 21))
        self.TrainerIDlineEdit.setObjectName("TrainerIDlineEdit")

        self.DeviceIDlineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.DeviceIDlineEdit.setGeometry(QtCore.QRect(160, 60, 21, 21))
        self.DeviceIDlineEdit.setObjectName("DeviceIDlineEdit")

        self.StatusCodeLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.StatusCodeLineEdit.setGeometry(QtCore.QRect(160, 100, 31, 21))
        self.StatusCodeLineEdit.setObjectName("StatusCodeLineEdit")

        self.stepDelayLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.stepDelayLineEdit.setGeometry(QtCore.QRect(160, 250, 31, 21))
        self.stepDelayLineEdit.setObjectName("stepDelayLineEdit")



    
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 150, 253, 22))
        self.widget.setObjectName("widget")



        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setObjectName("label_5")

        self.horizontalLayout.addWidget(self.label_5)

        self.CCWradBtn = QtWidgets.QRadioButton(parent=self.widget)
        self.CCWradBtn.setObjectName("CCWradBtn")

        self.horizontalLayout.addWidget(self.CCWradBtn)

        self.CWradBtn = QtWidgets.QRadioButton(parent=self.widget)
        self.CWradBtn.setObjectName("CWradBtn")

        self.horizontalLayout.addWidget(self.CWradBtn)

        self.widget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(50, 200, 202, 22))
        self.widget1.setObjectName("widget1")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.label_4 = QtWidgets.QLabel(parent=self.widget1)
        self.label_4.setObjectName("label_4")

        self.horizontalLayout_2.addWidget(self.label_4)

        self.FullstepRadBtn = QtWidgets.QRadioButton(parent=self.widget1)
        self.FullstepRadBtn.setObjectName("FullstepRadBtn")

        self.horizontalLayout_2.addWidget(self.FullstepRadBtn)

        self.HalfStepRadBtn = QtWidgets.QRadioButton(parent=self.widget1)
        self.HalfStepRadBtn.setObjectName("HalfStepRadBtn")

        self.horizontalLayout_2.addWidget(self.HalfStepRadBtn)

        self.Enterpbtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Enterpbtn.setGeometry(QtCore.QRect(100, 290, 75, 24))
        self.Enterpbtn.setObjectName("Enterpbtn")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 436, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)



        self.Enterpbtn.clicked.connect(self.dataEntered)
        self.Enterpbtn.clicked.connect(self.secondscr)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def dataEntered(self):
        BinaryData = self.TrainerIDlineEdit.text() + self.DeviceIDlineEdit.text() 
        if self.CWradBtn.isChecked():
            BinaryData = BinaryData + "01"
        
        if self.CCWradBtn.isChecked():
            BinaryData = BinaryData + "11"

        if self.FullstepRadBtn.isChecked():
            BinaryData = BinaryData + "01"

        if self.HalfStepRadBtn.isChecked():
            BinaryData = BinaryData + "11"

        print(BinaryData)


        global Binary 
        Binary = BinaryData




    
    def findChecksum(self, k = 4):
   
    # Dividing sent message in packets of k bits.
    
        c1 = Ui_MainWindow.Binary[0:k]
        c2 = Ui_MainWindow.Binary[k:2*k]
        c3 = Ui_MainWindow.Binary[2*k:3*k]
        c4 = Ui_MainWindow.Binary[3*k:4*k]
 
    # Calculating the binary sum of packets
        Sum = bin(int(c1, 2)+int(c2, 2)+int(c3, 2)+int(c4, 2))[2:]
    
        # Adding the overflow bits
        if(len(Sum) > k):
            x = len(Sum)-k
            Sum = bin(int(Sum[0:x], 2)+int(Sum[x:], 2))[2:]
        if(len(Sum) < k):
            Sum = '0'*(k-len(Sum))+Sum
    
        # Calculating the complement of sum
        Checksum = ''
        for i in Sum:
            if(i == '1'):
                Checksum += '0'
            else:
                Checksum += '1'
        return Checksum




    def secondscr(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SecondWindow()
        self.ui.setupUi(self.window)
        self.window.show()





    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Trainer ID"))
        self.label_2.setText(_translate("MainWindow", "Device ID"))
        self.label_3.setText(_translate("MainWindow", "Status Code"))
        self.label_8.setText(_translate("MainWindow", "ms"))
        self.stepDelayLineEdit.setText(_translate("MainWindow", "000"))
        self.label_7.setText(_translate("MainWindow", "Step Delay"))
        self.Enterpbtn.setText(_translate("MainWindow", "Enter"))
        self.TrainerIDlineEdit.setText(_translate("MainWindow", "00"))
        self.DeviceIDlineEdit.setText(_translate("MainWindow", "00"))
        self.StatusCodeLineEdit.setText(_translate("MainWindow", "000"))
        self.label_5.setText(_translate("MainWindow", "Rotation"))
        self.CCWradBtn.setText(_translate("MainWindow", "Counter clockwise"))
        self.CWradBtn.setText(_translate("MainWindow", "Clockwise"))
        self.label_4.setText(_translate("MainWindow", "Step Size"))
        self.FullstepRadBtn.setText(_translate("MainWindow", "Full Step"))
        self.HalfStepRadBtn.setText(_translate("MainWindow", "Half Step"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
